name: Auto Formatter

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
  
env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    runs-on: ubuntu-latest
    permissions: # Job-level permissions configuration starts here
      contents: write # 'write' access to repository contents
      pull-requests: write # 'write' access to pull requests
    env:
      CONFIG_PATH: ${{ github.event.inputs.config-path }}
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: echo $CONFIG_PATH & cd $CONFIG_PATH && ls
      - name: Format
        run: cd $CONFIG_PATH && cargo fmt
      - name: update
        run: |
          cd $CONFIG_PATH
          if ! git diff --exit-code; then
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git commit -am 'GITHUB ACTIONS: auto-formatter'
            git push origin HEAD:${GITHUB_REF##*/}
          fi