name: Auto Formatter

on:
  push:
    branches: ["*"]

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'GITHUB ACTIONS') }}
    permissions: # Job-level permissions configuration starts here
      contents: write # 'write' access to repository contents
      pull-requests: write # 'write' access to pull requests
    steps:
      - uses: actions/checkout@v4
      - name: Format
        run: cargo fmt
      - name: Verify Diff
        id: verify_diff
        run: |
          git diff --exit-code
          echo "::set-output name=changed::$(if [ $? -eq 0 ]; then echo 'false'; else echo 'true'; fi)"
      - name: update
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -am 'GITHUB ACTIONS: auto-formatter'
          git push origin HEAD:${GITHUB_REF##*/}
